"""
Stage 10 — Publishing / export layer.

Produces:
  - TeacherKnowledgePackage.json  (canonical, machine-readable)
  - LessonPlan.pdf                (period-by-period teaching plan)
  - TeacherGuide.pdf              (concept reference + gap analysis)
  - AssessmentPack.pdf            (questions, then answer key)

PDFs are built with ReportLab's platypus flowables so long content paginates
correctly instead of overflowing.
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path

from app.config import settings
from app.models.schemas import ExportManifest, TeacherKnowledgePackage

logger = logging.getLogger("gyantra.exporter")

ACCENT = "#0d9488"  # teal — matches the frontend accent
INK = "#1e293b"
MUTED = "#64748b"


def _escape(text: str) -> str:
    """Escape text for ReportLab's mini-HTML paragraph markup."""
    if not text:
        return ""
    out = (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )
    return out


def export_package(pkg: TeacherKnowledgePackage, job_id: str) -> ExportManifest:
    """Write all export artifacts for a completed package."""
    out_dir = Path(settings.export_dir) / job_id
    out_dir.mkdir(parents=True, exist_ok=True)

    manifest = ExportManifest()

    # --- JSON (always succeeds; it's the canonical artifact) ---
    json_path = out_dir / "TeacherKnowledgePackage.json"
    json_path.write_text(
        json.dumps(pkg.model_dump(mode="json"), indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    manifest.json_path = str(json_path)

    # --- PDFs (best-effort: a PDF failure must not fail the job) ---
    for name, builder, attr in (
        ("LessonPlan.pdf", _build_lesson_plan_pdf, "lesson_plan_pdf_path"),
        ("TeacherGuide.pdf", _build_teacher_guide_pdf, "teacher_guide_pdf_path"),
        ("AssessmentPack.pdf", _build_assessment_pdf, "assessment_pack_pdf_path"),
    ):
        path = out_dir / name
        try:
            builder(pkg, str(path))
            setattr(manifest, attr, str(path))
        except (ImportError, OSError, ValueError, KeyError) as exc:
            logger.error("failed to build %s: %s", name, exc)

    return manifest


# ── shared PDF scaffolding ───────────────────────────────────────────────────


def _styles():
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm

    ss = getSampleStyleSheet()

    def mk(name, **kw):
        base = kw.pop("parent", ss["BodyText"])
        return ParagraphStyle(name, parent=base, **kw)

    return {
        "title": mk(
            "GTitle", parent=ss["Title"], fontSize=24, leading=29,
            textColor=ACCENT, spaceAfter=4 * mm, alignment=TA_LEFT,
        ),
        "subtitle": mk("GSub", fontSize=11, leading=15, textColor=MUTED, spaceAfter=6 * mm),
        "h1": mk(
            "GH1", parent=ss["Heading1"], fontSize=16, leading=20,
            textColor=ACCENT, spaceBefore=6 * mm, spaceAfter=2.5 * mm,
        ),
        "h2": mk(
            "GH2", parent=ss["Heading2"], fontSize=12.5, leading=16,
            textColor=INK, spaceBefore=4 * mm, spaceAfter=1.5 * mm,
        ),
        "h3": mk(
            "GH3", parent=ss["Heading3"], fontSize=10.5, leading=14,
            textColor=MUTED, spaceBefore=3 * mm, spaceAfter=1 * mm,
        ),
        "body": mk("GBody", fontSize=9.8, leading=14.5, spaceAfter=2 * mm),
        "mono": mk("GMono", fontName="Courier", fontSize=8.6, leading=12, spaceAfter=2 * mm),
        "small": mk("GSmall", fontSize=8.4, leading=11.5, textColor=MUTED),
    }


def _doc(path: str, title: str):
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.platypus import SimpleDocTemplate

    return SimpleDocTemplate(
        path,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
        title=title,
        author="Gyantra",
    )


def _page_footer(canvas, doc):
    """Page number + attribution on every page."""
    canvas.saveState()
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(MUTED)
    canvas.drawString(18 * 2.83465, 10 * 2.83465, "Generated by Gyantra")
    canvas.drawRightString(
        doc.pagesize[0] - 18 * 2.83465, 10 * 2.83465, f"Page {doc.page}"
    )
    canvas.restoreState()


def _header(pkg: TeacherKnowledgePackage, st: dict, doc_title: str) -> list:
    from reportlab.platypus import Paragraph, Spacer
    from reportlab.lib.units import mm

    dp = pkg.document_profile
    story = [Paragraph(_escape(doc_title), st["title"])]

    bits = []
    if dp:
        for label, val in (
            ("Subject", dp.subject), ("Grade", dp.grade), ("Topic", dp.topic),
            ("Board", dp.board), ("Difficulty", dp.difficulty.value.title()),
        ):
            if val:
                bits.append(f"<b>{_escape(label)}:</b> {_escape(val)}")
    if pkg.metadata.source_file:
        bits.append(f"<b>Source:</b> {_escape(pkg.metadata.source_file)}")

    if bits:
        story.append(Paragraph(" &nbsp;·&nbsp; ".join(bits), st["subtitle"]))
    story.append(Spacer(1, 2 * mm))
    return story


def _bullets(items, st, style_key="body") -> list:
    """Render a list as indented bullet paragraphs."""
    from reportlab.platypus import Paragraph

    # Indentation belongs to the style, not the Paragraph constructor.
    bullet_style = st.get(f"{style_key}_bullet")
    if bullet_style is None:
        from reportlab.lib.styles import ParagraphStyle
        from reportlab.lib.units import mm

        bullet_style = ParagraphStyle(
            f"{style_key}Bullet",
            parent=st[style_key],
            leftIndent=5 * mm,
            bulletIndent=1 * mm,
            spaceAfter=1.2 * mm,
        )
        st[f"{style_key}_bullet"] = bullet_style

    out = []
    for item in items:
        text = _escape(str(item)).strip()
        if not text:
            continue
        out.append(Paragraph(text, bullet_style, bulletText="•"))
    return out


def _multiline(text: str, st: dict, style_key: str = "body") -> list:
    """Split a text blob into paragraphs, preserving line structure."""
    from reportlab.platypus import Paragraph

    out = []
    for raw_line in str(text or "").split("\n"):
        line = raw_line.strip()
        if not line:
            continue
        out.append(Paragraph(_escape(line), st[style_key]))
    return out


def _info_table(rows: list[tuple[str, str]], st: dict):
    """Two-column key/value table with the house style."""
    from reportlab.lib import colors
    from reportlab.lib.units import mm
    from reportlab.platypus import Paragraph, Table, TableStyle

    data = [
        [Paragraph(f"<b>{_escape(k)}</b>", st["small"]), Paragraph(_escape(v), st["small"])]
        for k, v in rows
        if v
    ]
    if not data:
        return None
    tbl = Table(data, colWidths=[38 * mm, 130 * mm])
    tbl.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("LINEBELOW", (0, 0), (-1, -2), 0.3, colors.HexColor("#e2e8f0")),
            ]
        )
    )
    return tbl


# ── 1. Lesson Plan PDF ───────────────────────────────────────────────────────


def _build_lesson_plan_pdf(pkg: TeacherKnowledgePackage, path: str) -> None:
    from reportlab.lib.units import mm
    from reportlab.platypus import KeepTogether, PageBreak, Paragraph, Spacer

    st = _styles()
    story = _header(pkg, st, "Lesson Plan")

    plan = pkg.teaching_plan
    ke = pkg.knowledge_extraction
    concept_names = {c.id: c.name for c in (ke.concepts if ke else [])}

    # --- plan overview ---
    if plan:
        story.append(Paragraph("Plan Overview", st["h1"]))
        tbl = _info_table(
            [
                ("Total periods", str(plan.total_periods)),
                ("Minutes per period", str(plan.default_minutes_per_period)),
                ("Why this structure", plan.adaptation_rationale),
            ],
            st,
        )
        if tbl:
            story.append(tbl)
            story.append(Spacer(1, 3 * mm))

    # --- learning objectives ---
    if ke and ke.learning_objectives:
        story.append(Paragraph("Learning Objectives", st["h2"]))
        story.extend(_bullets(ke.learning_objectives, st))

    if ke and ke.prerequisites_list:
        story.append(Paragraph("Prerequisites", st["h2"]))
        story.extend(_bullets(ke.prerequisites_list, st))

    # --- period detail ---
    content_by_period = {c.period_id: c for c in pkg.classroom_content}
    activities_by_period: dict[str, list] = {}
    for a in pkg.activities:
        for pid in a.linked_period_ids:
            activities_by_period.setdefault(pid, []).append(a)

    if plan:
        for period in plan.periods:
            story.append(PageBreak())
            story.append(
                Paragraph(
                    f"Period {period.number}: {_escape(period.title)}", st["h1"]
                )
            )
            meta_rows = [
                ("Duration", f"{period.estimated_minutes} minutes"),
                (
                    "Concepts",
                    ", ".join(
                        concept_names.get(cid, cid) for cid in period.key_concepts
                    ),
                ),
                ("Lesson arc", period.flow_summary),
            ]
            tbl = _info_table(meta_rows, st)
            if tbl:
                story.append(tbl)
                story.append(Spacer(1, 3 * mm))

            if period.objectives:
                story.append(Paragraph("Objectives", st["h2"]))
                story.extend(_bullets([o.text for o in period.objectives], st))

            if period.prerequisite_review:
                story.append(Paragraph("Review First", st["h2"]))
                story.extend(_bullets(period.prerequisite_review, st))

            content = content_by_period.get(period.id)
            if content:
                if content.warmup:
                    story.append(Paragraph("Entry Ticket / Warm-up", st["h2"]))
                    story.extend(_multiline(content.warmup, st))

                if content.teacher_script:
                    story.append(Paragraph("Teacher Script", st["h2"]))
                    story.extend(_multiline(content.teacher_script, st))

                if content.blackboard_notes:
                    story.append(Paragraph("Blackboard Notes", st["h2"]))
                    story.extend(_multiline(content.blackboard_notes, st, "mono"))

                if content.checkpoint_questions:
                    story.append(Paragraph("Checkpoint Questions", st["h2"]))
                    story.extend(_bullets(content.checkpoint_questions, st))

                if content.exit_ticket:
                    story.append(Paragraph("Exit Ticket", st["h2"]))
                    story.extend(_multiline(content.exit_ticket, st))

                if content.homework:
                    story.append(Paragraph("Homework", st["h2"]))
                    story.extend(_multiline(content.homework, st))

                if content.mentor_moment:
                    story.append(Paragraph("Mentor Moment", st["h2"]))
                    story.append(
                        Paragraph(
                            f"<i>{_escape(content.mentor_moment)}</i>", st["body"]
                        )
                    )
                    story.append(
                        Paragraph(
                            "(Pedagogical support — not drawn from the source document)",
                            st["small"],
                        )
                    )

            acts = activities_by_period.get(period.id, [])
            if acts:
                story.append(Paragraph("Activities for this period", st["h2"]))
                for a in acts:
                    story.append(
                        Paragraph(
                            f"<b>{_escape(a.title)}</b> "
                            f"({_escape(a.activity_type.value.replace('_', ' '))}, "
                            f"{a.duration_minutes} min)",
                            st["body"],
                        )
                    )

    doc = _doc(path, "Gyantra Lesson Plan")
    doc.build(story, onFirstPage=_page_footer, onLaterPages=_page_footer)


# ── 2. Teacher Guide PDF ─────────────────────────────────────────────────────


def _build_teacher_guide_pdf(pkg: TeacherKnowledgePackage, path: str) -> None:
    from reportlab.lib.units import mm
    from reportlab.platypus import PageBreak, Paragraph, Spacer

    st = _styles()
    story = _header(pkg, st, "Teacher Guide")

    ke = pkg.knowledge_extraction
    concept_names = {c.id: c.name for c in (ke.concepts if ke else [])}

    # --- concept reference ---
    if ke and ke.concepts:
        story.append(Paragraph("Concept Reference", st["h1"]))
        for c in ke.concepts:
            tag = " [core]" if c.is_core else ""
            story.append(
                Paragraph(
                    f"<b>{_escape(c.name)}</b>{tag} "
                    f"<font color='{MUTED}' size='8'>"
                    f"({_escape(c.difficulty.value)} · {_escape(c.bloom_level.value)})</font>",
                    st["h3"],
                )
            )
            if c.description:
                story.append(Paragraph(_escape(c.description), st["body"]))
            if c.source_ref and c.source_ref.pages:
                pages = ", ".join(str(p) for p in c.source_ref.pages)
                story.append(Paragraph(f"Source pages: {pages}", st["small"]))

    # --- definitions ---
    if ke and ke.definitions:
        story.append(Paragraph("Definitions", st["h1"]))
        for d in ke.definitions:
            story.append(
                Paragraph(f"<b>{_escape(d.term)}</b> — {_escape(d.text)}", st["body"])
            )

    # --- formulas ---
    if ke and ke.formulas:
        story.append(Paragraph("Formulas", st["h1"]))
        for f in ke.formulas:
            story.append(Paragraph(f"<b>{_escape(f.name)}</b>", st["h3"]))
            if f.latex:
                story.append(Paragraph(_escape(f.latex), st["mono"]))
            if f.explanation:
                story.append(Paragraph(_escape(f.explanation), st["body"]))

    # --- worked examples ---
    if ke and ke.examples:
        story.append(Paragraph("Examples", st["h1"]))
        for e in ke.examples:
            if e.title:
                story.append(Paragraph(_escape(e.title), st["h3"]))
            story.extend(_multiline(e.text, st))

    # --- activities ---
    if pkg.activities:
        story.append(PageBreak())
        story.append(Paragraph("Activity Bank", st["h1"]))
        for a in pkg.activities:
            story.append(Paragraph(_escape(a.title), st["h2"]))
            tbl = _info_table(
                [
                    ("Type", a.activity_type.value.replace("_", " ").title()),
                    ("Duration", f"{a.duration_minutes} minutes"),
                    ("Materials", ", ".join(a.materials) or "None required"),
                    (
                        "Concepts",
                        ", ".join(
                            concept_names.get(cid, cid) for cid in a.linked_concept_ids
                        ),
                    ),
                ],
                st,
            )
            if tbl:
                story.append(tbl)
                story.append(Spacer(1, 2 * mm))
            if a.teacher_instructions:
                story.append(Paragraph("Instructions", st["h3"]))
                story.extend(_multiline(a.teacher_instructions, st))
            if a.expected_student_response:
                story.append(Paragraph("Expected student response", st["h3"]))
                story.append(Paragraph(_escape(a.expected_student_response), st["body"]))
            if a.success_criteria:
                story.append(Paragraph("Success criteria", st["h3"]))
                story.append(Paragraph(_escape(a.success_criteria), st["body"]))

    # --- gap analysis ---
    ga = pkg.gap_analysis
    if ga and ga.misconceptions:
        story.append(PageBreak())
        story.append(Paragraph("Learning Gap Analysis", st["h1"]))
        if ga.remediation_summary:
            story.append(Paragraph(_escape(ga.remediation_summary), st["body"]))
            story.append(Spacer(1, 2 * mm))

        for m in ga.misconceptions:
            story.append(
                Paragraph(
                    f"{_escape(m.misconception)} "
                    f"<font color='{MUTED}' size='8'>[{m.severity.value}]</font>",
                    st["h3"],
                )
            )
            tbl = _info_table(
                [
                    ("Diagnostic", m.diagnostic_question),
                    ("Wrong answer to expect", m.expected_wrong_answer),
                    ("Remediation", m.remedial_action),
                ],
                st,
            )
            if tbl:
                story.append(tbl)
                story.append(Spacer(1, 2 * mm))

    # --- validation summary ---
    v = pkg.validation
    if v:
        story.append(PageBreak())
        story.append(Paragraph("Validation Report", st["h1"]))
        tbl = _info_table(
            [
                ("Overall", v.overall_status.value.upper()),
                ("Schema", v.schema_check.status.value),
                ("Consistency", v.consistency_check.status.value),
                ("Pedagogy", v.pedagogical_check.status.value),
                (
                    "Grounding",
                    f"{v.grounding_check.status.value} "
                    f"(hallucination risk {v.grounding_check.hallucination_risk:.0%})",
                ),
            ],
            st,
        )
        if tbl:
            story.append(tbl)
            story.append(Spacer(1, 3 * mm))

        if v.consistency_check.issues:
            story.append(Paragraph("Consistency notes", st["h3"]))
            story.extend(_bullets(v.consistency_check.issues, st, "small"))
        if v.pedagogical_check.notes:
            story.append(Paragraph("Pedagogical notes", st["h3"]))
            story.extend(_bullets(v.pedagogical_check.notes, st, "small"))
        if v.grounding_check.ungrounded_claims:
            story.append(Paragraph("Claims to review against the source", st["h3"]))
            story.extend(_bullets(v.grounding_check.ungrounded_claims, st, "small"))

    doc = _doc(path, "Gyantra Teacher Guide")
    doc.build(story, onFirstPage=_page_footer, onLaterPages=_page_footer)


# ── 3. Assessment Pack PDF ───────────────────────────────────────────────────


def _build_assessment_pdf(pkg: TeacherKnowledgePackage, path: str) -> None:
    from reportlab.lib.units import mm
    from reportlab.platypus import PageBreak, Paragraph, Spacer

    st = _styles()
    story = _header(pkg, st, "Assessment Pack")

    ap = pkg.assessments
    if not ap:
        story.append(Paragraph("No assessments were generated.", st["body"]))
        _doc(path, "Gyantra Assessment Pack").build(story)
        return

    items = ap.items
    story.append(
        Paragraph(
            f"Total marks: <b>{items.total_marks}</b> &nbsp;·&nbsp; "
            f"{len(items.mcqs)} MCQs, {len(items.short_answers)} short answer, "
            f"{len(items.long_answers)} long answer, {len(items.numericals)} numerical",
            st["small"],
        )
    )
    story.append(Spacer(1, 4 * mm))

    q_no = 1

    if items.mcqs:
        story.append(Paragraph("Section A — Multiple Choice", st["h1"]))
        for m in items.mcqs:
            story.append(
                Paragraph(f"<b>Q{q_no}.</b> {_escape(m.stem)} <font size='8'>[{m.marks}]</font>", st["body"])
            )
            for o in m.options:
                story.append(
                    Paragraph(
                        f"&nbsp;&nbsp;&nbsp;<b>{_escape(o.key)}.</b> {_escape(o.text)}",
                        st["body"],
                    )
                )
            q_no += 1
        story.append(Spacer(1, 3 * mm))

    if items.short_answers:
        story.append(Paragraph("Section B — Short Answer", st["h1"]))
        for s in items.short_answers:
            story.append(
                Paragraph(
                    f"<b>Q{q_no}.</b> {_escape(s.question)} <font size='8'>[{s.marks}]</font>",
                    st["body"],
                )
            )
            q_no += 1
        story.append(Spacer(1, 3 * mm))

    if items.numericals:
        story.append(Paragraph("Section C — Numerical Problems", st["h1"]))
        for n in items.numericals:
            story.append(
                Paragraph(
                    f"<b>Q{q_no}.</b> {_escape(n.question)} <font size='8'>[{n.marks}]</font>",
                    st["body"],
                )
            )
            q_no += 1
        story.append(Spacer(1, 3 * mm))

    if items.long_answers:
        story.append(Paragraph("Section D — Long Answer", st["h1"]))
        for l in items.long_answers:
            story.append(
                Paragraph(
                    f"<b>Q{q_no}.</b> {_escape(l.question)} "
                    f"<font size='8'>[{l.marks} marks, ~{l.word_limit} words]</font>",
                    st["body"],
                )
            )
            q_no += 1

    # --- answer key on its own pages ---
    story.append(PageBreak())
    story.append(Paragraph("Answer Key &amp; Marking Scheme", st["h1"]))

    q_no = 1
    if items.mcqs:
        story.append(Paragraph("Section A — Multiple Choice", st["h2"]))
        for m in items.mcqs:
            story.append(
                Paragraph(
                    f"<b>Q{q_no}.</b> Correct: <b>{_escape(m.correct_key)}</b>"
                    + (f" — {_escape(m.explanation)}" if m.explanation else ""),
                    st["body"],
                )
            )
            q_no += 1

    if items.short_answers:
        story.append(Paragraph("Section B — Short Answer", st["h2"]))
        for s in items.short_answers:
            story.append(Paragraph(f"<b>Q{q_no}.</b> {_escape(s.model_answer)}", st["body"]))
            if s.key_points:
                story.extend(_bullets(s.key_points, st, "small"))
            q_no += 1

    if items.numericals:
        story.append(Paragraph("Section C — Numerical Problems", st["h2"]))
        for n in items.numericals:
            story.append(
                Paragraph(
                    f"<b>Q{q_no}.</b> Answer: <b>{_escape(n.answer)} {_escape(n.unit)}</b>",
                    st["body"],
                )
            )
            if n.solution_steps:
                story.extend(_bullets(n.solution_steps, st, "small"))
            q_no += 1

    if items.long_answers:
        story.append(Paragraph("Section D — Long Answer", st["h2"]))
        for l in items.long_answers:
            story.append(
                Paragraph(f"<b>Q{q_no}.</b> {_escape(l.marking_scheme)}", st["body"])
            )
            q_no += 1

    if ap.blueprint:
        story.append(Paragraph("Bloom's Taxonomy Distribution", st["h2"]))
        story.extend(
            _bullets(
                [f"{k.title()}: {v} marks" for k, v in sorted(ap.blueprint.items())],
                st,
                "small",
            )
        )

    doc = _doc(path, "Gyantra Assessment Pack")
    doc.build(story, onFirstPage=_page_footer, onLaterPages=_page_footer)
